# -*- coding: utf-8 -*-
"""
使用 Pillow 生成单词卡片图片
"""
import os
import random
import textwrap
from pathlib import Path
from typing import Dict

from PIL import Image, ImageDraw, ImageFont

# 主题色列表
THEME_COLORS = [
    (47, 79, 79), (75, 0, 130), (0, 100, 0), (139, 0, 0),
    (47, 47, 79), (74, 74, 106), (26, 26, 46), (22, 33, 62),
    (15, 52, 96), (83, 52, 131)
]

# 默认字体路径，如果找不到会报错
FONT_PATH = Path(__file__).parent / "assets" / "DejaVuSans.ttf"
FONT_BOLD_PATH = Path(__file__).parent / "assets" / "DejaVuSans-Bold.ttf"

def get_font(size: int, bold: bool = False) -> ImageFont.FreeTypeFont:
    """加载字体，处理找不到字体的情况"""
    path = FONT_BOLD_PATH if bold else FONT_PATH
    try:
        return ImageFont.truetype(str(path), size)
    except IOError:
        print(f"警告: 字体文件未找到 at {path}. 将使用 Pillow 默认字体。")
        return ImageFont.load_default()

def generate_card_image(word: Dict, plugin_dir: Path) -> str:
    """
    使用 Pillow 生成单词卡片图片。
    返回生成的图片路径。
    """
    width, height = 800, 1000
    bg_color = random.choice(THEME_COLORS)
    text_color = (255, 255, 255)
    
    # 创建画布
    image = Image.new("RGB", (width, height), bg_color)
    draw = ImageDraw.Draw(image)

    # 字体
    font_word = get_font(80, bold=True)
    font_phonetic = get_font(35)
    font_pos = get_font(30, bold=True)
    font_def = get_font(40)
    font_example = get_font(30)
    font_footer = get_font(20)

    padding = 60
    current_y = padding

    # 1. 单词
    word_text = word.get("word", "")
    draw.text((padding, current_y), word_text, font=font_word, fill=text_color)
    current_y += 120

    # 2. 音标
    phonetic_text = word.get("phonetic", "")
    if phonetic_text:
        draw.text((padding, current_y), phonetic_text, font=font_phonetic, fill=(200, 200, 200))
        current_y += 60

    # 分割线
    draw.line([(padding, current_y), (width - padding, current_y)], fill=(200, 200, 200), width=2)
    current_y += 40

    # 3. 词性和中文释义
    pos_text = (word.get("pos", "") or "WORD").upper()
    def_text = word.get("definition_cn", "")
    
    draw.text((padding, current_y), pos_text, font=font_pos, fill=text_color)
    current_y += 50
    
    # 自动换行
    wrapped_def = textwrap.wrap(def_text, width=35)
    for line in wrapped_def:
        draw.text((padding, current_y), line, font=font_def, fill=text_color)
        current_y += 55
    
    current_y += 40

    # 4. 例句
    example_text = word.get("example", "")
    if example_text:
        wrapped_example = textwrap.wrap(example_text, width=45)
        for line in wrapped_example:
            draw.text((padding, current_y), line, font=font_example, fill=(200, 200, 200))
            current_y += 45

    # 页脚
    draw.text((padding, height - 50), "Generated by AstrBot VocabCard", font=font_footer, fill=(150, 150, 150))

    # 保存图片
    output_path = plugin_dir / f"card_{word_text}.png"
    image.save(output_path)
    
    return str(output_path)

def download_font_if_not_exists():
    """如果字体不存在，则尝试下载"""
    if FONT_PATH.exists() and FONT_BOLD_PATH.exists():
        return

    import requests
    import zipfile
    import io

    FONT_URL = "https://github.com/dejavu-fonts/dejavu-fonts/releases/download/version_2_37/dejavu-fonts-ttf-2.37.zip"
    
    assets_dir = Path(__file__).parent / "assets"
    assets_dir.mkdir(exist_ok=True)

    print("字体文件不存在，正在下载 DejaVu 字体...")
    try:
        response = requests.get(FONT_URL, timeout=60)
        response.raise_for_status()

        with zipfile.ZipFile(io.BytesIO(response.content)) as z:
            # 从 zip 中提取需要的字体文件
            font_file_name = "dejavu-fonts-ttf-2.37/ttf/DejaVuSans.ttf"
            font_bold_file_name = "dejavu-fonts-ttf-2.37/ttf/DejaVuSans-Bold.ttf"
            
            with z.open(font_file_name) as zf, open(assets_dir / "DejaVuSans.ttf", 'wb') as f:
                f.write(zf.read())
            print(f"已保存字体到 {assets_dir / 'DejaVuSans.ttf'}")

            with z.open(font_bold_file_name) as zf, open(assets_dir / "DejaVuSans-Bold.ttf", 'wb') as f:
                f.write(zf.read())
            print(f"已保存粗体字体到 {assets_dir / 'DejaVuSans-Bold.ttf'}")

    except Exception as e:
        print(f"下载字体失败: {e}")
        print("请手动下载 DejaVu 字体 (dejavu-fonts-ttf-2.37.zip)，")
        print("并将 DejaVuSans.ttf 和 DejaVuSans-Bold.ttf 放入 'assets' 文件夹中。")

# 在模块加载时检查并下载字体
download_font_if_not_exists()
