# -*- coding: utf-8 -*-
"""
使用 Pillow 生成单词卡片图片
"""
import random
import textwrap
from pathlib import Path
from typing import Dict, List

from PIL import Image, ImageDraw, ImageFont

from .constants import THEME_COLORS

# 默认字体路径，如果找不到会报错
FONT_PATH = Path(__file__).parent / "assets" / "MiSans-Regular.ttf"
FONT_BOLD_PATH = Path(__file__).parent / "assets" / "MiSans-Regular.ttf"
# FONT_BOLD_PATH = Path(__file__).parent / "assets" / "NotoSansSC-Bold.ttf"

def get_font(size: int, bold: bool = False) -> ImageFont.FreeTypeFont:  
    """加载字体，处理找不到字体的情况"""
    path = FONT_BOLD_PATH if bold else FONT_PATH
    try:
        return ImageFont.truetype(str(path), size)
    except IOError:
        print(f"警告: 字体文件未找到 at {path}. 将使用 Pillow 默认字体。")
        return ImageFont.load_default()

def generate_multi_word_card_image(words: List[Dict], plugin_dir: Path) -> str:
    """
    将多个单词生成到一张图片上。
    返回生成的图片路径。
    """
    width = 800
    padding = 50
    line_height_sm = 35
    line_height_md = 45
    line_height_lg = 60
    word_block_space = 40
    item_top_margin = 15

    # --- 字体 ---
    font_word = get_font(40, bold=True)
    font_phonetic = get_font(28)
    font_pos = get_font(28, bold=True)
    font_def = get_font(32)
    font_example = get_font(28)
    font_footer = get_font(20)
    
    # --- 动态计算高度 ---
    current_y = padding
    for word in words:
        current_y += line_height_lg  # word
        if word.get("phonetic"):
            current_y += line_height_sm # phonetic
        
        if word.get("pos"):
            current_y += item_top_margin
            current_y += line_height_sm # pos

        def_text = word.get("definition_cn", "")
        wrapped_def = textwrap.wrap(def_text, width=40)
        current_y += item_top_margin
        current_y += len(wrapped_def) * line_height_md # definition

        example_text = word.get("example", "")
        if example_text:
            current_y += item_top_margin
            wrapped_example = textwrap.wrap(example_text, width=50)
            current_y += len(wrapped_example) * line_height_sm # example

        current_y += word_block_space # block spacing

    height = current_y + 50 # Add footer space

    # --- 绘制 ---
    bg_color = random.choice(THEME_COLORS)
    text_color = (255, 255, 255)
    image = Image.new("RGB", (width, height), bg_color)
    draw = ImageDraw.Draw(image)

    current_y = padding
    for i, word in enumerate(words):
        # 绘制分割线
        if i > 0:
            draw.line([(padding, current_y - word_block_space // 2), (width - padding, current_y - word_block_space // 2)], fill=(200, 200, 200, 100), width=1)

        # 1. 单词
        word_text = word.get("word", "")
        draw.text((padding, current_y), word_text, font=font_word, fill=text_color)
        current_y += line_height_lg

        # 2. 音标
        phonetic_text = word.get("phonetic", "")
        if phonetic_text:
            draw.text((padding, current_y), phonetic_text, font=font_phonetic, fill=(200, 200, 200))
            current_y += line_height_sm

        # 3. 词性
        pos_text = (word.get("pos", "") or "").upper()
        if pos_text:
            current_y += item_top_margin
            draw.text((padding, current_y), pos_text, font=font_pos, fill=text_color)
            current_y += line_height_sm

        # 4. 中文释义
        def_text = word.get("definition_cn", "")
        wrapped_def = textwrap.wrap(def_text, width=40)
        current_y += item_top_margin
        for line in wrapped_def:
            draw.text((padding, current_y), line, font=font_def, fill=(220, 220, 220))
            current_y += line_height_md
        
        # 5. 例句
        example_text = word.get("example", "")
        if example_text:
            current_y += item_top_margin
            wrapped_example = textwrap.wrap(example_text, width=50)
            for line in wrapped_example:
                draw.text((padding, current_y), line, font=font_example, fill=(200, 200, 200))
                current_y += line_height_sm

        current_y += word_block_space

    # 页脚
    draw.text((padding, height - 40), "Generated by AstrBot VocabCard", font=font_footer, fill=(150, 150, 150))

    # 保存图片
    output_path = plugin_dir / f"card_multi_{random.randint(1000, 9999)}.png"
    image.save(output_path)
    
    return str(output_path)


def generate_card_image(word: Dict, plugin_dir: Path) -> str:
    """
    使用 Pillow 生成单词卡片图片。
    返回生成的图片路径。
    """
    width, height = 800, 1000
    bg_color = random.choice(THEME_COLORS)
    text_color = (255, 255, 255)
    
    # 创建画布
    image = Image.new("RGB", (width, height), bg_color)
    draw = ImageDraw.Draw(image)

    # 字体
    font_word = get_font(80, bold=True)
    font_phonetic = get_font(35)
    font_pos = get_font(30, bold=True)
    font_def = get_font(40)
    font_example = get_font(30)
    font_footer = get_font(20)

    padding = 60
    current_y = padding

    # 1. 单词
    word_text = word.get("word", "")
    draw.text((padding, current_y), word_text, font=font_word, fill=text_color)
    current_y += 120

    # 2. 音标
    phonetic_text = word.get("phonetic", "")
    if phonetic_text:
        draw.text((padding, current_y), phonetic_text, font=font_phonetic, fill=(200, 200, 200))
        current_y += 60

    # 分割线
    draw.line([(padding, current_y), (width - padding, current_y)], fill=(200, 200, 200), width=2)
    current_y += 40

    # 3. 词性和中文释义
    pos_text = (word.get("pos", "") or "WORD").upper()
    def_text = word.get("definition_cn", "")
    
    draw.text((padding, current_y), pos_text, font=font_pos, fill=text_color)
    current_y += 50
    
    # 自动换行
    wrapped_def = textwrap.wrap(def_text, width=35)
    for line in wrapped_def:
        draw.text((padding, current_y), line, font=font_def, fill=text_color)
        current_y += 55
    
    current_y += 40

    # 4. 例句
    example_text = word.get("example", "")
    if example_text:
        wrapped_example = textwrap.wrap(example_text, width=45)
        for line in wrapped_example:
            draw.text((padding, current_y), line, font=font_example, fill=(200, 200, 200))
            current_y += 45

    # 页脚
    draw.text((padding, height - 50), "Generated by AstrBot VocabCard", font=font_footer, fill=(150, 150, 150))

    # 保存图片
    output_path = plugin_dir / f"card_{word_text}.png"
    image.save(output_path)
    
    return str(output_path)
